# Generated by Django 5.0.3 on 2024-03-15 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Personality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("abbrv", models.CharField(max_length=1)),
                (
                    "dichotomy",
                    models.CharField(
                        choices=[
                            ("I/E", "Introversion/Extroversion"),
                            ("S/N", "Sensing/Intuition"),
                            ("T/F", "Thinking/Feeling"),
                            ("J/P", "Judging/Perceiving"),
                        ],
                        max_length=3,
                    ),
                ),
                ("describe", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PersonalityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "combo",
                    models.CharField(
                        choices=[
                            ("INTJ", "INTJ"),
                            ("INTP", "INTP"),
                            ("ENTJ", "ENTJ"),
                            ("ENTP", "ENTP"),
                            ("INFJ", "INFJ"),
                            ("INFP", "INFP"),
                            ("ENFJ", "ENFJ"),
                            ("ENFP", "ENFP"),
                            ("ISTJ", "ISTJ"),
                            ("ISFJ", "ISFJ"),
                            ("ESTJ", "ESTJ"),
                            ("ESFJ", "ESFJ"),
                            ("ISTP", "ISTP"),
                            ("ISFP", "ISFP"),
                            ("ESTP", "ESTP"),
                            ("ESFP", "ESFP"),
                        ],
                        max_length=4,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("describe", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "dichotomy",
                    models.CharField(
                        choices=[
                            ("I/E", "Introversion/Extroversion"),
                            ("S/N", "Sensing/Intuition"),
                            ("T/F", "Thinking/Feeling"),
                            ("J/P", "Judging/Perceiving"),
                        ],
                        max_length=50,
                    ),
                ),
                ("text", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="UserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
