# Generated by Django 5.0.3 on 2024-03-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalitytype",
            name="combo",
            field=models.CharField(
                choices=[
                    ("INTJ", "INTJ"),
                    ("INTP", "INTP"),
                    ("ENTJ", "ENTJ"),
                    ("ENTP", "ENTP"),
                    ("INFJ", "INFJ"),
                    ("INFP", "INFP"),
                    ("ENFJ", "ENFJ"),
                    ("ENFP", "ENFP"),
                    ("ISTJ", "ISTJ"),
                    ("ISFJ", "ISFJ"),
                    ("ESTJ", "ESTJ"),
                    ("ESFJ", "ESFJ"),
                    ("ISTP", "ISTP"),
                    ("ISFP", "ISFP"),
                    ("ESTP", "ESTP"),
                    ("ESFP", "ESFP"),
                ],
                max_length=4,
            ),
        ),
    ]
