# Generated by Django 5.0.3 on 2024-03-19 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_alter_personalitytype_combo"),
        ("users", "0002_userinfo_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userresponse",
            name="user",
        ),
        migrations.AddField(
            model_name="userresponse",
            name="user_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.userinfo",
            ),
        ),
    ]
