# Generated by Django 5.0.3 on 2024-03-23 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_remove_userresponse_user_userresponse_user_info"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPersonality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("introversion", models.FloatField()),
                ("extroversion", models.FloatField()),
                ("sensing", models.FloatField()),
                ("intuition", models.FloatField()),
                ("thinking", models.FloatField()),
                ("feeling", models.FloatField()),
                ("judging", models.FloatField()),
                ("perceiving", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
