# Generated by Django 5.0.3 on 2024-03-12 04:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_remove_userresponse_resume_userresponse_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalitytype",
            old_name="description",
            new_name="describe",
        ),
    ]
