# Generated by Django 5.0.4 on 2024-04-21 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="has_company",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="has_resume",
        ),
    ]
