# Generated by Django 5.2.3 on 2025-06-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userinfo_has_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='has_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='has_resume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
