# Generated by Django 5.0.2 on 2024-02-09 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="address",
            new_name="street",
        ),
    ]
