# Generated by Django 5.0.2 on 2024-03-01 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[("Mr", "Mr"), ("Mrs", "Mrs"), ("Ms", "Ms")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_recruiter", models.BooleanField(default=False)),
                ("is_applicant", models.BooleanField(default=False)),
                ("has_resume", models.BooleanField(default=False)),
                ("has_company", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
