# Generated by Django 5.0.3 on 2024-03-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "M"), ("Female", "F")],
                max_length=10,
                null=True,
            ),
        ),
    ]
