# Generated by Django 5.0.3 on 2024-03-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userinfo_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="d_o_b",
            field=models.DateField(blank=True, null=True),
        ),
    ]
