# Generated by Django 5.0.3 on 2024-03-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userinfo_d_o_b"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
    ]
