# Generated by Django 5.0.3 on 2024-03-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpersonality",
            name="graph",
            field=models.ImageField(blank=True, null=True, upload_to="save_chart"),
        ),
    ]
