# Generated by Django 5.0.3 on 2024-04-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_userpersonality_graph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpersonality",
            name="graph",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
