# Generated by Django 5.0.2 on 2024-02-10 06:21

import django.db.models.deletion
import job.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0002_rename_address_company_street"),
        ("resume", "0003_alter_resume_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(max_length=100)),
                ("pay", models.PositiveIntegerField(default=14)),
                ("describe", models.TextField()),
                ("tasks", models.TextField()),
                ("ideal", models.TextField()),
                ("available", models.BooleanField(default=False)),
                (
                    "download",
                    models.FileField(
                        blank=True, null=True, upload_to=job.models.rename_file
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("resume", models.ManyToManyField(null=True, to="resume.resume")),
            ],
        ),
    ]
