# Generated by Django 5.0.2 on 2024-02-19 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
        ("resume", "0003_alter_resume_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="resume",
            field=models.ManyToManyField(to="resume.resume"),
        ),
    ]
