# Generated by Django 5.0.2 on 2024-02-29 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobpost",
            old_name="ideal",
            new_name="ideal_candidate",
        ),
        migrations.RenameField(
            model_name="jobpost",
            old_name="title",
            new_name="job_title",
        ),
    ]
