# Generated by Django 5.0.2 on 2024-02-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0005_alter_applyjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Remote", "Remote"),
                    ("Onsite", "Onsite"),
                    ("Hybrid", "Hybrid"),
                ],
                default="Onsite",
                max_length=20,
                null=True,
            ),
        ),
    ]
