# Generated by Django 5.0.2 on 2024-02-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0006_jobpost_job_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="location",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
