# Generated by Django 5.0.2 on 2024-02-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0007_remove_jobpost_location_jobpost_city_jobpost_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Declined", "Declined"),
                    ("Pending", "Pending"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Remote", "Remote"),
                    ("Onsite", "Onsite"),
                    ("Hybrid", "Hybrid"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
