# Generated by Django 5.0.4 on 2024-04-21 01:57

import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0003_alter_education_end_year_alter_education_start_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=resume.models.rename_image
            ),
        ),
    ]
