# Generated by Django 5.0.2 on 2024-03-01 06:39

import django.db.models.deletion
import resume.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Transportation", "Transportation"),
                            ("Pharmaceutical", "Pharmaceutical"),
                            ("Telecommunications", "Telecommunications"),
                            ("Manufacturing", "Manufacturing"),
                            ("Mining", "Mining"),
                            ("Hospitality", "Hospitality"),
                            ("Media and News", "Media and News"),
                            ("Agriculture", "Agriculture"),
                            ("Computer and Technology", "Computer and Technology"),
                            ("Education", "Education"),
                            ("Finance and Economics", "Finance and Economics"),
                            ("Health Care", "Health Care"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("profession", models.CharField(blank=True, max_length=100, null=True)),
                ("years", models.IntegerField(blank=True, null=True)),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to=resume.models.rename_file
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
