# Generated by Django 5.0.2 on 2024-02-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
